project: "OpenWorldSSL"
name: "NACH"
save_dir: "result/${name}"
data_dir: "../Datasets"

# ---------------------------------------------------------------- #
dataset:
  name: "imagenet"
  num_class: 100
  label_num: 50
  label_ratio: 0.5

# ---------------------------------------------------------------- #
wandb:
  mode: "online"
  notes: null
  id: null
  tags_dataset: ${dataset.name}
  tags_model: ${model.backbone.name}

seed: 12345
resume:
  checkpoint: null # Always non-null if eval
  strict: true

# ---------------------------------------------------------------- #
model:
  pretrained: "./pretrained/simclr_cifar_10.pth.tar"
  backbone:
    name: "resnet18"

  fixmatch_threshold: 0.95

loss: # Cross-entropy
  label_smoothing: 0.1

metric: # Accuracy
  top_k: [ 1 ]

# ---------------------------------------------------------------- #
dataloader:
  train:
    batch_size: 512  # per-GPU  (approx. 10GB)
    num_workers: 8  # per-process
  valid:
    batch_size: 100  # per-GPU
    num_workers: 8 # per-process

# ---------------------------------------------------------------- #
optimizer:
  name: "sgd"
  lr: 1e-1  # 0.001 * batch_size_per_gpu * num_accum * num_gpus
  momentum: 0.9
  weight_decay: 5.0e-4

scheduler:
  name: "cos"     # "cos" "custom" "constant"
  warmup:
    start_factor: 0.01
    epochs: 10
  decay:
    epochs: 190  # warmup + decay should be the same as trainer.max_epochs
    min_lr: 1.0e-6

# ---------------------------------------------------------------- #
trainer:
  fp16: true
  max_epochs: 200
  print_interval_iters: 50
  valid_interval_epochs: 10
  clip_grad: 100.0
  num_accum: 1