project: "OpenWorldSSL"
name: "NACH"
save_dir: "result/${dataset.name}/${name}"
data_dir: "../Datasets"

# ---------------------------------------------------------------- #
dataset:
  name: "cifar100"
  num_class: 100
  label_num: 50
  label_ratio: 0.5

# ---------------------------------------------------------------- #
wandb:
  mode: "online"
  notes: null
  id: null
  tags_dataset: ${dataset.name}
  tags_model: ${model.backbone.name}

seed: 12345
resume:
  checkpoint: null # Always non-null if eval
  strict: true

# ---------------------------------------------------------------- #
model:
  pretrained: "../Datasets/pretrained/simclr_cifar_100.pth.tar"
  backbone:
    name: "resnet18"
    is_freeze: true
  fixmatch_threshold: 0.95

loss:


# ---------------------------------------------------------------- #
dataloader:
  train:
    batch_size: 512  # per-GPU  (approx. 10GB)
    num_workers: 8  # per-process
  valid:
    batch_size: 100  # per-GPU
    num_workers: 8 # per-process

# ---------------------------------------------------------------- #
optimizer:
  name: "sgd"
  lr: 1e-1  # 0.001 * batch_size_per_gpu * num_accum * num_gpus
  momentum: 0.9
  weight_decay: 5.0e-4

scheduler:
  name: "cos"     # "cos" "custom" "constant"

# ---------------------------------------------------------------- #
trainer:
  fp16: true
  max_epochs: 200
  print_interval_iters: 50
  valid_interval_epochs: 1
  clip_grad: 100.0
  num_accum: 1